# Configuración del Pipeline de Cobranzas FACO
# ================================================

pipeline:
  name: "faco_cobranzas_pipeline"
  version: "1.1.0"
  environment: "production"

# Configuración de BigQuery
bigquery:
  project_id: "mibot-222814"
  dataset_staging: "BI_USA"
  dataset_analytics: "BI_USA"
  
# Configuración del Stage de Asignación
stage_asignacion:
  table_name: "bi_P3fV4dWNeMkN5RJMhV8e_stg_asignacion"
  stored_procedure: "bi_P3fV4dWNeMkN5RJMhV8e_sp_asignacion"
  source_table: "batch_P3fV4dWNeMkN5RJMhV8e_asignacion"
  calendar_table: "bi_P3fV4dWNeMkN5RJMhV8e_dash_calendario_v5"
  
  # Llaves primarias
  primary_keys:
    - "cod_luna"
    - "cod_cuenta" 
    - "archivo"
    
  # Campos para merge
  merge_fields:
    - "estado_cartera"
    - "saldo_dia"
    - "fecha_actualizacion"
    
  # Configuración de detección automática
  auto_detection:
    enabled: true
    filter_by_date: "FECHA_ASIGNACION"
    fallback_message: "No se encontraron archivos para la fecha especificada"
    
  # Modos de ejecución
  execution_modes:
    default: "INCREMENTAL"
    options:
      - "INCREMENTAL"  # Solo procesa registros >= fecha_proceso
      - "FULL"         # Reprocesa todo el histórico
      
  # Filtros de archivos
  file_filters:
    auto_detect: true    # Si archivo_filter es NULL, detecta automáticamente
    manual_override: true # Permite especificar filtros manuales
    
  # Reglas de negocio
  business_rules:
    objetivos_recupero:
      AL_VCTO: 0.15
      ENTRE_4_Y_15D: 0.25
      TEMPRANA: 0.20
      DEFAULT: 0.20
      
    categorias_vencimiento:
      dias_por_vencer: [30, 60, 90]
      
    tipos_cartera:
      TEMPRANA: "TEMPRANA"
      CF_ANN: "CUOTA_FRACCIONAMIENTO" 
      AN: "ALTAS_NUEVAS"
      DEFAULT: "OTRAS"
      
    fraccionamiento:
      values: ["FRACCIONADO", "NORMAL"]
      default: "NORMAL"
      
# Configuración de logging
logging:
  level: "INFO"
  format: "json"
  capture_metrics: true
  log_detected_files: true  # Nuevo: registra archivos detectados automáticamente
  
# Configuración de calidad de datos
data_quality:
  tests_enabled: true
  success_rate_threshold: 95.0
  tests:
    - "unique_primary_keys"
    - "not_null_validation"
    - "objetivo_recupero_range"
    - "categoria_vencimiento_values"
    - "calendar_join_completeness"
    
# Configuración de monitoreo
monitoring:
  alerts:
    duration_threshold_minutes: 30
    volume_variation_threshold: 50.0
    quality_threshold: 95.0
    no_files_detected: true  # Nuevo: alerta si no se detectan archivos
    
# Configuración de optimización
optimization:
  partitioning:
    enabled: true
    field: "fecha_asignacion"
    type: "DATE"
  clustering:
    enabled: true
    fields: ["cod_luna", "tipo_cartera", "segmento_gestion"]
